### ISSUE TITLE
VSCode extension customers can acquire and interact with global .NET installs

### ISSUE THREAD

**Issue by nagilson** [dotnet/vscode-dotnet-runtime#1052]
# EPIC - Add Global .NET SDK Installs for DevKit, & Others

See https://github.com/dotnet/vscode-dotnet-runtime/pull/1046 for an overview of major changes made and our plan.
cc
@marcpopMSFT
@baronfel @leslierichardson95  @webreidi 
@JL03-Yue 

## Basic API 
- [x] Change the API to match the specifications requested
https://github.com/dotnet/vscode-dotnet-runtime/issues/763
https://github.com/dotnet/vscode-dotnet-runtime/pull/1081
- [x] Create an API to list the newest available SDKs and Runtimes/
https://github.com/dotnet/vscode-dotnet-runtime/issues/764
- [x] Create an API to suggest what version of the .NET SDK or Runtime to Install
https://github.com/dotnet/vscode-dotnet-runtime/pull/791
- [x] Create a resolver that figures out what installer you need to install based on your request

## Windows and Mac
- [x] Create the installer that installs the .NET SDK globally for windows.
https://github.com/dotnet/vscode-dotnet-runtime/issues/763
https://github.com/dotnet/vscode-dotnet-runtime/pull/1081
- [x] Add logic to read the registry to prevent overhead of installing when it is not needed.
- [x] Create the installer that installs the .NET SDK globally for Mac.
- [x] Perform and improve error handling that comes out from the existing installer.

## Existing Code Improvement
- [x] Migrate to a new cache for web-requests so the cache does not get stale.
https://github.com/dotnet/vscode-dotnet-runtime/issues/416
https://github.com/dotnet/vscode-dotnet-runtime/pull/799

## Global Runtimes
- [ ] Create the ability to manage global runtimes.
https://github.com/dotnet/vscode-dotnet-runtime/issues/1055
- [ ] Add an API to list the installed global runtimes on the machine.
https://github.com/dotnet/vscode-dotnet-runtime/issues/1055

## Threat Model
- [x] Create a threat model for our global extension installs.
https://github.com/dotnet/vscode-dotnet-runtime/issues/1053
- [x] Add sign-checking to .NET installers that we download from the interwebs. 
- [x] Investigate if/how we can sign and validate signatures in typescript.

## Linux
- [x] Add the ability to manage global installs on Linux
https://github.com/dotnet/vscode-dotnet-runtime/issues/763
https://github.com/dotnet/vscode-dotnet-runtime/pull/1046
- [x] Get a base-feature set working for Ubuntu 
- [x] Add support for other distros. Namely, RHEL
https://github.com/dotnet/vscode-dotnet-runtime/issues/1054
- [ ] Add support for distros that are subsets of the supported distro types, a.k.a. CentOS, Fedora, Debian
https://github.com/dotnet/vscode-dotnet-runtime/issues/1054
- [x] Add documentation for the community to explain how they can add their own distros
https://github.com/dotnet/vscode-dotnet-runtime/issues/1054
- [x] Verify that the install can correctly add and install Microsoft feed packages across different situations
- [x] Verify that the install can correctly install Distro Feed Packages across different contexts
- [x] Create a vendor testing plan to have different versions and distro combinations tested.
- [ ] Work with the VS Code team to get the sudo prompter to show who is requesting elevation on Ubuntu
https://github.com/dotnet/vscode-dotnet-runtime/issues/1056

## Nice to Haves (Not Planned Yet)
- [x] Add the global uninstall command.
- [ ] Add the global update command to allow callers to suggest an update instead of installing.
- [ ] Add global.json parsing.
- [ ] Add localization to all parts of the extension. https://github.com/dotnet/vscode-dotnet-runtime/issues/1130

## Existing Extension Repair
- [ ] Fix issues with telemetry and existing dotnet paths if concurrent extension requests occur from different extensions.
https://github.com/dotnet/vscode-dotnet-runtime/issues/1010
https://github.com/dotnet/vscode-dotnet-runtime/issues/1009
- [x] Update the incorrect licensing information in the existing extension code.
https://github.com/dotnet/vscode-dotnet-runtime/issues/905
- [x] Fix incorrect error logging
https://github.com/dotnet/vscode-dotnet-runtime/issues/885

## Miscellaneous and Concluding Items
- [x] Instruct internal teams on how they can use our extension.
https://github.com/dotnet/vscode-dotnet-runtime/issues/763
- [x] Re-brand the Extensions and their documentation to meet the new purposes.
https://github.com/dotnet/vscode-dotnet-runtime/pull/935
- [x] Launch the 2.0 version of the SDK Extension.
- [x] Communicate with Education Bundle Team so we can change the install default to global.
