### ISSUE TITLE
Consolidated Fixes for C#/DevKit extension user experience

### ISSUE THREAD

**Issue by baronfel** [dotnet/vscode-dotnet-runtime#1300]
This tracks the issues we need to tackle to fix the user experience for the Runtime extension experience in C#/DevKit:

* [ ] Extend script download/installation timeout to 10m
* [ ] Merge the Axios PR for better caching and error handling
* [ ] Execute the install scripts with verbose logging for better diagnostics
* [ ] Investigate and solve repeated writes of the install-scripts
* [ ] Investigate if `chmod` of the scripts 'takes'
* [ ] Analyze telemetry from timeouts and search for commonalities that can be resolved
